apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-ingress
  namespace: argocd
  annotations:
    nginx.ingress.kubernetes.io/app-root: /argocd
spec:
  ingressClassName: nginx
  rules:
    - host: k8s-asus.calvarado04.com
      http:
        paths:
          - path: /argocd
            pathType: Prefix
            backend:
              service:
                name: argo-cd-1651634282-server
                port: 
                  number: 80
